DEVICE_PATH := device/sts/a03br
BOARD_VENDOR := sts
BOARD_DEVICE := a03br
TARGET_DEVICE := a03br
TARGET_SOC := pxa1928
TARGET_BOARD_PLATFORM := mrvl
BOARD_USES_MRVL_HARDWARE := true
# BOARD_RAMDISK_USE_LZMA := true
# build option
ALLOW_MISSING_DEPENDENCIES := true
BOARD_SUPPRESS_SECURE_ERASE := true
DISABLE_ASHMEM_TRACKING := true
BOARD_NO_SECURE_DISCARD := true
TARGET_NO_SENSOR_PERMISSION_CHECK := true
# TARGET_REQUIRES_SYNCHRONOUS_SETSURFACE := true
TARGET_OTA_ASSERT_DEVICE := TAB-A03-BR,a03br
# TARGET_FS_CONFIG_GEN := $(DEVICE_PATH)/config.fs

#disable
BOARD_PROVIDES_LIBRIL := false
BOARD_PROVIDES_RILD := false
BOARD_HAS_NFC := false
BOARD_HAS_RADIO := false
BOARD_HAS_HDMI := false
WITHOUT_CHECK_API := true
TARGET_NO_BOOTLOADER := true

# Architecture
TARGET_ARCH := arm64
TARGET_ARCH_VARIANT := armv8-a
TARGET_CPU_ABI := arm64-v8a
TARGET_CPU_ABI2 :=
TARGET_CPU_VARIANT := generic
TARGET_CPU_VARIANT_RUNTIME := cortex-a53
TARGET_2ND_ARCH := arm
TARGET_2ND_ARCH_VARIANT := armv7-a-neon
TARGET_2ND_CPU_ABI := armeabi-v7a
TARGET_2ND_CPU_ABI2 := armeabi
TARGET_2ND_CPU_VARIANT := generic
TARGET_2ND_VARIANT_RUNTIME := cortex-a53
TARGET_USES_64_BIT_BINDER := true
TARGET_CPU_ABI_LIST_64_BIT := $(TARGET_CPU_ABI)
TARGET_CPU_ABI_LIST_32_BIT := $(TARGET_2ND_CPU_ABI),$(TARGET_2ND_CPU_ABI2)
TARGET_CPU_ABI_LIST := $(TARGET_CPU_ABI_LIST_64_BIT),$(TARGET_CPU_ABI_LIST_32_BIT)


#ota
AB_OTA_UPDATER := false

# Bootloader
TARGET_BOOTLOADER_BOARD_NAME := TAB-A03-BR
TARGET_NO_FACTORYIMAGE :=true
TARGET_NO_BOOTLOADER := true
TARGET_NO_RADIOIMAGE := true

# Display
DEVICE_RESOLUTION := 1280x800
LANDSCAPE_RESOLUTION := 1280x800
PORTRAIT_RESOLUTION := 800x1280

#prop
TARGET_SYSTEM_PROP := $(DEVICE_PATH)/system.prop

# File systems
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 10485760
BOARD_FLASH_BLOCK_SIZE := 131072
BOARD_BOOTIMAGE_PARTITION_SIZE := 16777216
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1988100096
BOARD_SYSTEMIMAGE_PARTITION_TYPE := ext4
BOARD_USERDATAIMAGE_FILE_SYSTEM_TYPE := ext4
BOARD_UMS_LUNFILE := "/sys/class/android_usb/f_mass_storage/lun0/file"
BOARD_USES_MMCUTILS := true
BOARD_HAS_NO_MISC_PARTITION := true

# Kernel
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_CMDLINE :=
BOARD_KERNEL_PAGESIZE := 2048
BOARD_RAMDISK_OFFSET := 0x01000000
BOARD_KERNEL_TAGS_OFFSET := 0x00000100
BOARD_KERNEL_OFFSET := 0x00008000
BOARD_SECOND_OFFSET := 0x00f00000

BOARD_MKBOOTIMG_ARGS := \
     --base $(BOARD_KERNEL_BASE) \
     --pagesize $(BOARD_KERNEL_PAGESIZE) \
     --kernel_offset $(BOARD_KERNEL_OFFSET) \
     --ramdisk_offset $(BOARD_RAMDISK_OFFSET) \
     --tags_offset $(BOARD_KERNEL_TAGS_OFFSET) \
     --second_offset $(BOARD_SECOND_OFFSET) \
     --cmdline "$(BOARD_KERNEL_CMDLINE)"

TARGET_IGNORES_KERNEL_HEADERS := true
TARGET_KERNEL_ARCH := arm64
TARGET_KERNEL_HEADER_ARCH := arm64

# Kernel - prebuilt
TARGET_FORCE_PREBUILT_KERNEL := true
ifeq ($(TARGET_FORCE_PREBUILT_KERNEL),true)
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/prebuilt/kernel
PRODUCT_COPY_FILES += \
    $(DEVICE_PATH)/prebuilt/kernel:kernel
endif

# Vendor partition configure
# BOARD_USES_VENDORIMAGE := false

# Recovery
TARGET_USERIMAGES_USE_EXT4 := true
RECOVERY_SDCARD_ON_DATA := true
BOARD_RECOVERY_SWIPE := true
BOARD_SUPPRESS_EMMC_WIPE := true
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/root/etc/recovery.fstab
BOARD_HAS_NO_REAL_SDCARD := true
TW_NO_EXFAT := true


# Security patch level
# VENDOR_SECURITY_PATCH := 2018-03-05

# include vendor/sts/a03br/BoardConfigVendor.mk

# SELinux
#BOARD_SEPOLICY_DIRS := \
	#$(DEVICE_PATH)/sepolicy/
#BOARD_SECCOMP_POLICY += $(DEVICE_PATH)/seccomp_policy

SELINUX_IGNORE_NEVERALLOWS := true
BOARD_HAS_NO_SELECT_BUTTON := true
TW_INCLUDE_CRYPTO := false
TW_USE_TOOLBOX := false
TW_THEME := landscape_mdpi
TW_EXTRA_LANGUAGES := false
TW_USE_INPUT_EVENTS := true
TW_INCLUDE_INJECTTWRP := false
TW_INCLUDE_FB2PNG := false
TW_INPUT_BLACKLIST := hbtp_vm
#TW_INPUT_BLACKLIST := "isl29023\x0alsm9ds1_mag"
TW_SCREEN_BLANK_ON_BOOT := true
TW_NO_SCREEN_TIMEOUT := false
TW_EXCLUDE_BASH := true
TW_EXCLUDE_NANO := true
TW_EXCLUDE_LZMA := false
TW_EXCLUDE_SED := true
TW_EXCLUDE_MTP := true
TW_NO_BZIP2 := true
TW_EXCLUDE_DEFAULT_USB_INIT := true
TW_EXCLUDE_TAR := true
TW_EXCLUDE_ENCRYPTED_BACKUPS := true
TW_EXCLUDE_TWRPAPP := true
TW_EXCLUDE_SUPERSU := true
TW_EXCLUDE_PYTHON := true
TW_DEFAULT_LANGUAGE := en
TW_EXCLUDE_GZIP := false
TW_EXCLUDE_XZ := true
TW_NO_HAPTICS := true
TW_ALWAYS_RMRF := true
TW_EXCLUDE_TZDATA := true
TW_NO_EXFAT_FUSE := true
TW_NO_USB_STORAGE := true
TW_INCLUDE_DUMLOCK := false
TARGET_USES_LOGD := false
TWRP_INCLUDE_LOGCAT := false
TW_NO_REBOOT_BOOTLOADER := true
